### ISSUE TITLE
preference reversal with wealth level

### ISSUE THREAD

**Issue by ole-peters** [LMLhub/Discounting#2]
There's another type of preference reversal we could mention: as wealth levels change, preferences can change. This is really interesting, e.g. it predicts that poor people would be more impatient for which there is evidence.

See this tweet
https://twitter.com/ole_b_peters/status/1104324262427541504

Thoughts?

**Comment by diomavro** [comment]
I agree it is very interesting. Though, what would that look like in a formal sense? Would you define some wealth, x and some wealth x+e and show that the discount rate is higher for the second case?  Does this not require stochasticity?

**Comment by diomavro** [comment]
Hm, it is not clear to me why the poorer person will choose differently to the richer person. In which case will it matter? In our framework, it looks to like the term x(t_0) cancels out. What would have to change?

**Comment by alex-adamou** [comment]
I think the best way to see PR mathematically is to consider g_a - g_b as a
function of the variable in question, e.g. H as we do for case A, x(t_0) as
suggested here, or any of the other variables in the problem. H and x(t_0)
seem especially interesting ones to vary. The payment amounts and delay
seem more "built in" to the problem.

PR happens when this function crosses the horizontal axis.

g_a - g_b depends on x(t_0) only in case B. It's true that x(t_0) drops out
in the small-payment approximation that we made to get a closed-form
discount factor in the text. That's understandable: in effect, we took the
large-wealth limit, so we don't expect wealth to appear. The full solution
for g_a - g_b has x(t_0) dependence. We can evaluate the function
numerically and plot it.

AA

--
Alex Adamou | Director
London Mathematical Laboratory
+447779324026

**Comment by diomavro** [comment]
I'm not convinced that the x(t_0) matters, even in my weird non approximated initial formulation the term does not appear. I think it requires the bet amount to also be multiplicative not just the wealth.

**Comment by ole-peters** [comment]
Yes, this happens in case B. I think the figure in the tweet is very clear: change the initial wealth and see the slopes change. 
https://twitter.com/ole_b_peters/status/1104324262427541504

It could be just a sentence or two added to section 3.3, along with a figure like in the tweet. Given that we can't assume that people know the difference between adding up and multiplying, I would try to keep things as simple as possible.
What's nice about that figure is that it has the same format as the others, nothing new, really, to get one's head around.

But let's plot g_a-g_b, @alex-adamou. If it doesn't complicate things too much, we can add it. I like the paper as it is at the moment: short, clear, simple.

**Comment by diomavro** [comment]
It seems intuitive that the result should be that the growth rate will decrease over time until it is trivially small. Then you want to look at the average growth rate if someone starts with less wealth and compare it to more? I'm not sure this is going to get different results, but also how would you simulate when it is optimal for the poor person to switch preferences(if it is a function of wealth)?

**Comment by ole-peters** [comment]
This is how the figure looks that @alex-adamou was suggesting (parameters from the tweet).
[ga_gb.pdf](https://github.com/LMLhub/Discounting/files/3232255/ga_gb.pdf)

**Comment by diomavro** [comment]
Hm very interesting... intermediate levels of wealth switch the preferences and then as you approach infinity you revert back to initial? So a 0 wealth has the same pref as an infinite wealth?

**Comment by alex-adamou** [comment]
All wealth to the right of the zero-crossing will have g_a-g_b<0. The
difference gets smaller as wealth increases because the decision becomes
increasingly irrelevant!

AA

--
Alex Adamou | Director
London Mathematical Laboratory
+447779324026

**Comment by diomavro** [comment]
Oh, sorry I misread it, there is only one crossing of the zero axis then! It's a little hard to see the intuition behind this but it's very interesting! Great work.

**Comment by diomavro** [comment]
I'm playing around with this. I think it occurs because the log is not monotonically increasing in the ratio? For instance, I am under the impression that a sufficient condition for rich and poor to prefer the same lottery is: x_a>x_0 e^{i(t_b-t_0)}, then it does not occur?

**Comment by alex-adamou** [comment]
Hi Dio, here is my simple intuition for wealth-dependent PR in the multiplicative elastic setup (case B). Even though the payments are cash amounts, I must conceptualise them here as wealth multipliers (or exponential growth rates, but multiples are easier to do in my head than logarithms). I need to work out which option gives me the fastest implied growth under immediate repetition. Suppose I start with $100. Ignore background interest for the moment (r = 0) and let the payments be $10 after 1 year or $25 after 2 years. The early payment multiplies my wealth by 1.10 pa and the later payment by sqrt(1.25) = 1.12 pa, so I prefer the later payment. Now make my starting wealth smaller, say $10. You can see immediately that the implied growth from the payments is rather different: doubling my wealth every year is better than 3.5x every two years (2.00 pa vs 1.87 pa). So a poorer person prefers to be paid quickly. The background interest has only a weak effect and doesn't change this intuitive picture. As r increases, the multipliers become more dominated by interest than payments, and so people of all wealths become more indifferent between the options. Does this help?

**Comment by diomavro** [comment]
Hey Alex, great explanation. Do you not think we should include this in the
paper? I think some intuition of this form is very helpful.

Le mar. 4 juin 2019 à 16:28, Alexander Adamou <notifications@github.com> a
écrit :

**Comment by diomavro** [comment]
I will write something up, one more thing here, if you can have this result
in Case B should you not ALSO have it in case A? I mean it looks like it
works even with r=0. I was under the impression that if r=0, then we would
collapse into A. Why does this not occur?

Le mar. 4 juin 2019 à 17:28, Alexander Adamou <notifications@github.com> a
écrit :

**Comment by bermanjoe** [comment]
Because when the dynamics are additive and given that the payment is a cash amount, the growth rate, and therefore the preference between A and B, doesn't depend on the initial wealth. The growth rate is simply the cash payment divided by the time interval. If the dynamics are multiplicative, the growth rate represents a fraction - say, x% per year. For a given cash payment, the value of x would then depend on the initial wealth.

**Comment by diomavro** [comment]
But it looks to me like the equivalent of setting k=0(Case A) is setting
r=0(Case B), and in that case, the dynamics are identical! Does this
reasoning not work: If the dynamics are identical, then the discounting is
identical.



Le mar. 4 juin 2019 à 17:43, Yonatan Berman <notifications@github.com> a
écrit :

**Comment by alex-adamou** [comment]
The intertemporal discounting problem is always presented as a choice between different cash payments (i.e. _ostensibly_ additive wealth changes) at different times. However, the underlying dynamics determine how these payments should be interpreted, which informs how we model repetition of the payments and how we compute growth rates. If the dynamics are additive, then we interpret the payments as they are presented, as additive wealth changes; if multiplicative, then we interpret them as wealth multipliers or, equivalently and illuminatingly, as additive changes in logarithmic wealth. So cases A and B are different, even when k=0 and r=0, because the payments are interpreted as different operations on wealth.

**Comment by diomavro** [comment]
Does this mean that you interpret that IF you have higher wealth, you
expect the choice to be different? That is, you expect that if you have 100
euros and the choices are 10% and 20%. Then when you have 1000 euros, you
still expect the choices to be 10% and 20%?

Le mar. 4 juin 2019 à 18:10, Alexander Adamou <notifications@github.com> a
écrit :

**Comment by diomavro** [comment]
FYI, I am aware this is just geometric Brownian motion, I am just trying to
make sure that that is what the reason is and not something else.

**Comment by alex-adamou** [comment]
We assume the choice is always presented between two fixed cash payments, which do not scale with initial wealth or any other variable in the problem. Translation of cash payments into wealth multipliers is not part of the problem presentation - it is part of our analysis. In other words, we treat x(t_0), Dt_a, and Dt_a as independent variables of the problem. Doubling x(t_0) does not double Dt_a.

The reason the choice depends on initial wealth in case B is that the wealth multipliers implied by the cash payments depend on the starting wealth AND these are what we seek to maximise (per unit time) when dynamics are multiplicative. It is also true that the implied wealth multipliers depend on the initial wealth in case A BUT we are not interested in them there, because the dynamics are additive.

**Comment by ole-peters** [comment]
I hope you're looking at the current version of the writing branch. I did
add the preference reversal in response to a change of initial wealth, at
the end of section 3.3. case B.

O

**Comment by bermanjoe** [comment]
One more thing - I added a line referring to this paper (https://pdfs.semanticscholar.org/58b5/6bccebd53026de7542ebde5020b2af2cf34e.pdf) which finds that poorer people discount differently from richer people. We need to think if it is worth digging deeper there or just leave it like that.

**Comment by bermanjoe** [comment]
Just letting you know - I just synced a revised version (in the writing branch).
