### ISSUE TITLE
didn't understand one paragraph

### ISSUE THREAD

**Issue by ole-peters** [LMLhub/Discounting#3]
...and marked it XXXOP: ...

Also: is it really true that hyperbolic discounting is always explained with some form of randomness? I also marked this XXXOP: ...

It just seems very natural to compute the rate of wealth accumulation, which gives us hyperbolic discounting. Surely someone must have noticed that.

**Comment by diomavro** [comment]
Hm, how does the labeling work? Do you choose to label "writing?" am I guaranteed that pulling writing will get me the latest one? 

I don't know about "randomness" but it usually is either a black box, which says 'assume people discount' OR if you are trying to explain WHY people discount, then yes, it is usually about some kind of lack of knowledge about some future event, I am not aware of any paper doing it otherwise. My supervisor told me this is not true and mentioned the "golden egg" paper we cite but as far I can see, they actually have the black box approach. 

I think most economists don't even know the Kelly Criteria, so it would surprise me if they applied a generalization.

**Comment by bermanjoe** [comment]
Yes, if you pull writing you should be able to read and edit the latest version.

**Comment by diomavro** [comment]
Some notes on Sozou: 
your value of cash flow in period t, is the value of the cash flow times the probability that you will survive until period t. So if you are 100% sure you will survive, you do not discount. 

To derive hyperbolic discounting, he simply assumes the probability of survival to be the hyperbolic discount rate s= 1/(1+k*t). 

The relationship between survival functions and hazard functions has a form -s'/s. So he finds that the hazard rate which gets you the corresponding survival function is the exponential function. 

I've added a sentence explaining if you think this is clear enough I will just go ahead and push otherwise I will add more, the paragraph now reads: 

"The reasoning behind the model of~\citet{sozou1998hyperbolic}, for example, is that agents do not know the hazard rate of a random event and learn about it over time through Bayesian updating. Thus, the longer an event does not occur, the more likely it is that it will not occur (decreasing estimated hazard rate). In other words, the agents have some prior on the arrival rate of the event, and the longer they wait without observing the event the more they judge that the arrival rate must be small. If the survival probability is to be equal to the hyperbolic discount rate, using the Laplace transform of the survival function, they show that the prior must be an exponential distribution. "

**Comment by diomavro** [comment]
Sorry I've added **two** sentences. The last one can sound better I think.
