### ISSUE TITLE
nomenclature for wealth dynamics

### ISSUE THREAD

**Issue by ole-peters** [LMLhub/Discounting#4]
Wealth dynamics consist of
1) add or multiply
2) period of repetition

Think of good terminology

**Comment by ole-peters** [comment]
use the following macros:

mode of repetition: \mode
period of repetition: \period

**Comment by bermanjoe** [comment]
I decided to stay with "time frame" at the moment, but I removed all its appearances until it is defined and put it in italics. So it only serves as a name for something we define properly. If anyone has a better suggestion, let me know since then the tree figure would need to be changed as well.

**Comment by alex-adamou** [comment]
Agree with Yonatan. We discussed this yesterday and there are good reasons why we used the vague term "time frame" initially. It's not really the repetition period that is being referred to here, rather the rule for computing it, i.e. whether one becomes free to act again after the chosen payment is received or after the time of the last possible payment. The repetition period is just an intermediate quantity in a growth rate calculation, determined by this rule.

**I suggest we leave the text alone and leave the issue open for now.** Let's see whether a concise and attractive way of referring to this idea dawns on one of us in a pensive moment.

[P.S. I have the sense that this is closely related to the concept of "opportunity cost". The later payment comes with an opportunity cost relative to the earlier payment in the elastic time frame, but not in the fixed time frame. But I'm worried about introducing an already-established idea, which could have other less appropriate meanings to economists.]

**Comment by diomavro** [comment]
I think the opportunity cost idea works as an interpretation but it's
fairly limited. This is because we do not specify the repetition option, we
simply say that the agent considers each option on it's own time horizon. I
think the concept of opportunity cost is abit wobbly when you do not say
exactly what the cost is. Usually you say the opportunity cost is the
second best option but here it is not clear what that means. I think a term
like "optionality" better captures the relative advantage of the quicker
option in elastic case.
